package crimemanagement;


import java.awt.Color;
import javax.swing.table.DefaultTableModel;

import javax.swing.*;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import javax.swing.table.DefaultTableCellRenderer;
//import org.json.simple.JSONObject;
import org.json.*;

public class CrimeRecords extends javax.swing.JFrame {
    
    static int size=35;
    static int violent_crime[]=new int[size];
    static int homicide[]=new int[size];
    //static int rape_legacy[]=new int[20];
    static int robbery[]=new int[size];
    static int aggravated_assault[]=new int[size];
    static int property_crime[]=new int[size];
    static int burglary[]=new int[size];
    static int larceny[]=new int[size];
    static int motor_vehicle_theft[]=new int[size];
    static int arson[]=new int[size];
    /*
    static int office_equipment[]=new int[20];
    static long miscellaneous[]=new long[20];
    static long not_specified[]=new long[20];
    static long consumable_goods[]=new long[20];
    static long locally_stolen_motor_vehicles[]=new long[20];
    static long firearms[]=new long[20];
    static long livestock[]=new long[20];
    static long household_goods[]=new long[20];
    static long jewelry_and_precious_metals[]=new long[20];
    static long currency_notes_etc[]=new long[20];
    static long clothing_and_furs[]=new long[20];
    static long telvisions_radio_stereos_etc[]=new long[20];
    
    static long value_office_equipment[]=new long[20];
    static long value_miscellaneous[]=new long[20];
    static long value_not_specified[]=new long[20];
    static long value_consumable_goods[]=new long[20];
    static long value_locally_stolen_motor_vehicles[]=new long[20];
    static long value_firearms[]=new long[20];
    static long value_livestock[]=new long[20];
    static long value_household_goods[]=new long[20];
    static long value_jewelry_and_precious_metals[]=new long[20];
    static long value_currency_notes_etc[]=new long[20];
    static long value_clothing_and_furs[]=new long[20];
    static long value_telvisions_radio_stereos_etc[]=new long[20];
    
    static long recover_office_equipment[]=new long[20];
    static long recover_miscellaneous[]=new long[20];
    static long recover_not_specified[]=new long[20];
    static long recover_consumable_goods[]=new long[20];
    static long recover_locally_stolen_motor_vehicles[]=new long[20];
    static long recover_firearms[]=new long[20];
    static long recover_livestock[]=new long[20];
    static long recover_household_goods[]=new long[20];
    static long recover_jewelry_and_precious_metals[]=new long[20];
    static long recover_currency_notes_etc[]=new long[20];
    static long recover_clothing_and_furs[]=new long[20];
    static long recover_telvisions_radio_stereos_etc[]=new long[20];
    */
    public CrimeRecords() {
        initComponents();
        setLocationRelativeTo(null);
        //jPanel2.setVisible(false);
        jTableCrime.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)jTableCrime.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        jTableCrime.setGridColor(Color.WHITE);
        jTableCrime.setForeground(Color.WHITE);
        
        jScrollPane2.setBackground(new Color(0,0,0,0));
        jScrollPane2.setOpaque(false);
        jTableCrime.setOpaque(false);
        ((DefaultTableCellRenderer)jTableCrime.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonOkRetrieve = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelDes1 = new javax.swing.JLabel();
        jLabelDes2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCrime = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jLabelPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonOkRetrieve.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonOkRetrieve.setText("Retrieve");
        jButtonOkRetrieve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonOkRetrieve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOkRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkRetrieveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOkRetrieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 80, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CRIME RECORDS INFORMATION");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, -1, -1));

        jLabelMn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelMn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMn.setText("-");
        jLabelMn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMnMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, 20, 20));

        jLabel10.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Year:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 305, -1, -1));

        jLabelDes1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabelDes1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDes1.setText("Here, in this page, you can find the total number of crimes occured in differeent field of the whole nation.");
        jPanel1.add(jLabelDes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 160, -1, -1));

        jLabelDes2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabelDes2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDes2.setText("The information is retrieved from The Federal Bureau of Investigation (FBI) the domestic intelligence and security service of the United States.");
        jPanel1.add(jLabelDes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 195, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an option", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 303, 280, -1));

        jTableCrime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTableCrime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Violent crime", "Homicide", "Robbery", "Assault", "Property crime", "Burglary", "Larcency", "Vehicle Theft", "Arson"
            }
        ));
        jScrollPane2.setViewportView(jTableCrime);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 850, 260));

        jButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackMouseClicked(evt);
            }
        });
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 60, 30));

        jLabelPicture.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPicture.setIcon(new javax.swing.ImageIcon("H:\\Java Crime\\CrimeManagement\\Java images\\crime record.jpg")); // NOI18N
        jLabelPicture.setText("jLabel1");
        jLabelPicture.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.add(jLabelPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkRetrieveActionPerformed
        
        String time = jComboBox1.getSelectedItem().toString();
        int item=Integer.parseInt(time);
        int index=item-1985;
        //1
        String tbData1[] = {String.valueOf(index+1985),String.valueOf(violent_crime[index]),String.valueOf(homicide[index])/*,String.valueOf(rape_legacy[index])*/,String.valueOf(robbery[index]),String.valueOf(aggravated_assault[index]),String.valueOf(property_crime[index]),String.valueOf(burglary[index]),String.valueOf(larceny[index]),String.valueOf(motor_vehicle_theft[index]),String.valueOf(arson[index])};
        DefaultTableModel tblModel = (DefaultTableModel)jTableCrime.getModel();
        tblModel.addRow(tbData1);
        /*
        //2
        String tbData2[] = {"Miscellaneous",String.valueOf(miscellaneous[index]),String.valueOf(value_miscellaneous[index]),String.valueOf(recover_miscellaneous[index])};
        tblModel.addRow(tbData2);
        
        //3
        String tbData3[] = {"Not Specified",String.valueOf(not_specified[index]),String.valueOf(value_not_specified[index]),String.valueOf(recover_not_specified[index])};
        tblModel.addRow(tbData3);
        
        //4
        String tbData4[] = {"Consumable goods",String.valueOf(consumable_goods[index]),String.valueOf(value_consumable_goods[index]),String.valueOf(recover_consumable_goods[index])};
        tblModel.addRow(tbData4);
        
        //5
        String tbData5[] = {"Locally stolen motor vehicles",String.valueOf(locally_stolen_motor_vehicles[index]),String.valueOf(value_locally_stolen_motor_vehicles[index]),String.valueOf(recover_locally_stolen_motor_vehicles[index])};
        tblModel.addRow(tbData5);
        
        //6
        String tbData6[] = {"firearms",String.valueOf(firearms[index]),String.valueOf(value_firearms[index]),String.valueOf(recover_firearms[index])};
        tblModel.addRow(tbData6);
        
        //7
        String tbData7[] = {"Livestock",String.valueOf(livestock[index]),String.valueOf(value_livestock[index]),String.valueOf(recover_livestock[index])};
        tblModel.addRow(tbData7);
        //8
        String tbData8[] = {"household_goods",String.valueOf(household_goods[index]),String.valueOf(value_household_goods[index]),String.valueOf(recover_household_goods[index])};
        tblModel.addRow(tbData8);
        
        //9
        String tbData9[] = {"Jewelry and precious metals",String.valueOf(jewelry_and_precious_metals[index]),String.valueOf(value_jewelry_and_precious_metals[index]),String.valueOf(recover_jewelry_and_precious_metals[index])};
        tblModel.addRow(tbData9);
        
        //10
        String tbData10[] = {"Currency notes etc",String.valueOf(currency_notes_etc[index]),String.valueOf(value_currency_notes_etc[index]),String.valueOf(recover_currency_notes_etc[index])};
        tblModel.addRow(tbData10);
        
        //11
        String tbData11[] = {"Clothing and furs",String.valueOf(clothing_and_furs[index]),String.valueOf(value_clothing_and_furs[index]),String.valueOf(recover_clothing_and_furs[index])};
        tblModel.addRow(tbData11);
        
        //12
        String tbData12[] = {"Telvisions radio stereos etc",String.valueOf(telvisions_radio_stereos_etc[index]),String.valueOf(value_telvisions_radio_stereos_etc[index]),String.valueOf(recover_telvisions_radio_stereos_etc[index])};
        tblModel.addRow(tbData12);*/
        
    }//GEN-LAST:event_jButtonOkRetrieveActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMnMouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackMouseClicked
        HomePageForPolice hgf = new HomePageForPolice();
        hgf.setVisible(true);
        hgf.pack();
        hgf.setLocationRelativeTo(null);
        hgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonBackMouseClicked

    
    static void mainCrime() throws JSONException{
        BufferedReader reader;
        String line=new String();
        StringBuffer response = new StringBuffer();
        HttpURLConnection connection=null;
        
        try{
            URL u = new URL("https://api.usa.gov/crime/fbi/sapi/api/summarized/estimates/national/1985/2019?api_key=type_your API KEY here");
            connection = (HttpURLConnection) u.openConnection();
            
            
            int status = connection.getResponseCode();
            System.out.println("code"+status);
            
            
            if(status>299){
                reader = new BufferedReader(new InputStreamReader(connection.getErrorStream()));
                
                while ((line = reader.readLine()) != null) {
                    response.append(line);
                }
                reader.close();
            }
            else{
                reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
                
                while ((line = reader.readLine()) != null) {
                    response.append(line);
                }
                reader.close();
            }
            //parse(response.toString());
            //System.out.println(response);*/
        }
        /*
        catch(Exception e){
            System.out.println(e);
        }*/
        
        catch(MalformedURLException e){
            e.printStackTrace();
        }
        catch(IOException e){
            e.printStackTrace();
        }
        finally{
            connection.disconnect();
        }
        //System.out.println(response);
        
        JSONObject myResponse = new JSONObject(response.toString());
        //System.out.println(myResponse);
        JSONArray array= (JSONArray)myResponse.get("results");
        //int arrayLength = ;
        System.out.println("Crime Records");
        System.out.println(array.length());
        
        for(int i=0; i<size; i++){
            
            //obj.setID(((Integer) row.get("ID")).longValue());
            JSONObject results = (JSONObject)array.get(i);
            int index=(int)results.get("year");
            int year=index-1985;
            
            violent_crime[year]= (int)results.get("violent_crime");
            homicide[year]= (int)results.get("homicide");
            //rape_legacy[year-2000]= (int)results.get("rape_legacy");
            robbery[year]= (int)results.get("robbery");
            aggravated_assault[year]= (int)results.get("aggravated_assault");
            property_crime[year]= (int)results.get("property_crime");
            burglary[year]= (int)results.get("burglary");
            larceny[year]= (int)results.get("larceny");
            motor_vehicle_theft[year]= (int)results.get("motor_vehicle_theft");
            arson[year]= (int)results.get("arson");
    
            /*
            office_equipment[i]= (int)results.get("office_equipment");
            miscellaneous[i]= (long)results.get("miscellaneous");
            not_specified[i] = (long)results.get("not_specified");
            consumable_goods[i] = (long)results.get("consumable_goods");
            locally_stolen_motor_vehicles[i] = (long)results.get("locally_stolen_motor_vehicles");
            firearms[i] = (long)results.get("firearms");
            livestock[i] = (long)results.get("livestock");
            household_goods[i] = (long)results.get("household_goods");
            jewelry_and_precious_metals[i] = (long)results.get("jewelry_and_precious_metals");
            currency_notes_etc[i] = (long)results.get("currency_notes_etc");
            clothing_and_furs[i] = (long)results.get("clothing_and_furs");
            telvisions_radio_stereos_etc[i] = (long)results.get("telvisions_radio_stereos_etc");
            
            value_office_equipment[i] = (long)results.get("office_equipment_stolen_value");
            value_miscellaneous[i] = (long)results.get("miscellaneous_stolen_value");
            value_not_specified[i] = (long)results.get("not_specified_stolen_value");
            value_consumable_goods[i] = (long)results.get("consumable_goods_stolen_value");
            value_locally_stolen_motor_vehicles[i] = (long)results.get("locally_stolen_motor_vehicles_stolen_value");
            value_firearms[i] = (long)results.get("firearms_stolen_value");
            value_livestock[i] = (long)results.get("livestock_stolen_value");
            value_household_goods[i] = (long)results.get("household_goods_stolen_value");
            value_jewelry_and_precious_metals[i] = (long)results.get("jewelry_and_precious_metals_stolen_value");
            value_currency_notes_etc[i] = (long)results.get("currency_notes_etc_stolen_value");
            value_clothing_and_furs[i] = (long)results.get("clothing_and_furs_stolen_value");
            value_telvisions_radio_stereos_etc[i] = (long)results.get("telvisions_radio_stereos_etc_stolen_value");
            
            recover_office_equipment[i] = (long)results.get("office_equipment_recovered_count");
            recover_miscellaneous[i] = (long)results.get("miscellaneous_recovered_count");
            recover_not_specified[i] = (long)results.get("not_specified_recovered_count");
            recover_consumable_goods[i] = (long)results.get("consumable_goods_recovered_count");
            recover_locally_stolen_motor_vehicles[i] = (long)results.get("locally_stolen_motor_vehicles_recovered_count");
            recover_firearms[i] = (long)results.get("firearms_recovered_count");
            recover_livestock[i] = (long)results.get("livestock_recovered_count");
            recover_household_goods[i] = (long)results.get("household_goods_recovered_count");
            recover_jewelry_and_precious_metals[i] = (long)results.get("jewelry_and_precious_metals_recovered_count");
            recover_currency_notes_etc[i] = (long)results.get("currency_notes_etc_recovered_count");
            recover_clothing_and_furs[i] = (long)results.get("clothing_and_furs_recovered_count");
            recover_telvisions_radio_stereos_etc[i] = (long)results.get("telvisions_radio_stereos_etc_recovered_count");
        */
        }
    }
    
    public static void main(String args[]) throws JSONException {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrimeRecords().setVisible(true);
            }
        });
        
        mainCrime();
        DutyOfficers.mainCaller();
        
        //}
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonOkRetrieve;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDes1;
    private javax.swing.JLabel jLabelDes2;
    private javax.swing.JLabel jLabelMn;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCrime;
    // End of variables declaration//GEN-END:variables
}
