package crimemanagement;


import javax.swing.JFrame;
import org.json.JSONArray;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import org.json.simple.JSONObject;
import org.json.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class DutyOfficers extends javax.swing.JFrame {

    
    static int size=35;
    static int year[]=new int[size];//=new ArrayList<>();
    static int male[]=new int[size];//ArrayList<String> male=new ArrayList<>();
    static int female[]=new int[size];//ArrayList<String> female=new ArrayList<>();
    static int agency[]=new int[size];
    
    
    public DutyOfficers() {
        initComponents();
        setLocationRelativeTo(null);
        jButtonOkRetrieve.setVisible(false);
        jLabelFemaleOfficer.setVisible(false);
        jLabelMaleOfficer.setVisible(false);
        jLabelOfficer.setVisible(false);
        jLabelAgency.setVisible(false);
        jLabelYear.setVisible(false);
        jTextFieldAgency.setVisible(false);
        jTextFieldFemaleOfficer.setVisible(false);
        jTextFieldMaleOfficer.setVisible(false);
        jTextFieldOfficer.setVisible(false);
        jComboBox1.setVisible(false);
        
        
        jButtonOkRetrieveForThana.setVisible(false);
        jScrollPane1.setVisible(false);
        jTableOfficer.setVisible(false);
        jTextFieldThana.setVisible(false);
        jLabelEnterThana.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldFemaleOfficer = new javax.swing.JTextField();
        jButtonOkRetrieve = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMn = new javax.swing.JLabel();
        jLabelYear = new javax.swing.JLabel();
        jLabelDes = new javax.swing.JLabel();
        jLabelDes1 = new javax.swing.JLabel();
        jLabelDes2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelFemaleOfficer = new javax.swing.JLabel();
        jLabelMaleOfficer = new javax.swing.JLabel();
        jTextFieldMaleOfficer = new javax.swing.JTextField();
        jTextFieldOfficer = new javax.swing.JTextField();
        jTextFieldAgency = new javax.swing.JTextField();
        jLabelOfficer = new javax.swing.JLabel();
        jLabelAgency = new javax.swing.JLabel();
        jLabelDes3 = new javax.swing.JLabel();
        jLabelDes4 = new javax.swing.JLabel();
        jLabelEnterThana = new javax.swing.JLabel();
        jTextFieldThana = new javax.swing.JTextField();
        jButtonOkRetrieveForThana = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOfficer = new javax.swing.JTable();
        jLabelDes5 = new javax.swing.JLabel();
        jLabelDesGoHome = new javax.swing.JLabel();
        jLabelDes7 = new javax.swing.JLabel();
        jButtonNational = new javax.swing.JButton();
        Individual = new javax.swing.JButton();
        jLabelPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldFemaleOfficer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldFemaleOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 500, 280, 30));

        jButtonOkRetrieve.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonOkRetrieve.setText("Retrieve");
        jButtonOkRetrieve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonOkRetrieve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOkRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkRetrieveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOkRetrieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 80, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INFORMATION ABOUT DUTY OFFICERS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 80, -1, -1));

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 30, -1, -1));

        jLabelMn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelMn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMn.setText("-");
        jLabelMn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMnMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 25, 20, 30));

        jLabelYear.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        jLabelYear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYear.setText("Year:");
        jPanel1.add(jLabelYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        jLabelDes.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabelDes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDes.setText("You can get the information about total appointed duty officers and");
        jPanel1.add(jLabelDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabelDes1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabelDes1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDes1.setText("agencies who give full time attention to duties which are incumbent on");
        jPanel1.add(jLabelDes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        jLabelDes2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabelDes2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDes2.setText("incubment on every citizen in the interests of community welfare and existence.");
        jPanel1.add(jLabelDes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an option", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 280, -1));

        jLabelFemaleOfficer.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        jLabelFemaleOfficer.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFemaleOfficer.setText("total female officer:");
        jPanel1.add(jLabelFemaleOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 505, -1, -1));

        jLabelMaleOfficer.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        jLabelMaleOfficer.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaleOfficer.setText("total male officer:");
        jPanel1.add(jLabelMaleOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 555, -1, -1));

        jTextFieldMaleOfficer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldMaleOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 550, 280, 30));

        jTextFieldOfficer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 600, 280, 30));

        jTextFieldAgency.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 450, 280, 30));

        jLabelOfficer.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        jLabelOfficer.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOfficer.setText("total officer:");
        jPanel1.add(jLabelOfficer, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, -1, -1));

        jLabelAgency.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        jLabelAgency.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgency.setText("total agency:");
        jPanel1.add(jLabelAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 455, -1, -1));

        jLabelDes3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabelDes3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDes3.setText("If you want to see the information of a");
        jPanel1.add(jLabelDes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, -1, -1));

        jLabelDes4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabelDes4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDes4.setText("specific area click on individual button and select a police station(thana) to see it's duty officers' list.");
        jPanel1.add(jLabelDes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jLabelEnterThana.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        jLabelEnterThana.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEnterThana.setText("Enter Thana:");
        jPanel1.add(jLabelEnterThana, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 395, -1, -1));

        jTextFieldThana.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldThana, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 280, 30));

        jButtonOkRetrieveForThana.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonOkRetrieveForThana.setText("Retrieve");
        jButtonOkRetrieveForThana.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonOkRetrieveForThana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOkRetrieveForThana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkRetrieveForThanaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOkRetrieveForThana, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 80, 30));

        jTableOfficer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTableOfficer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Duty Zone", "Officer's Name"
            }
        ));
        jScrollPane1.setViewportView(jTableOfficer);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, 140));

        jLabelDes5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabelDes5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDes5.setText("to go back to Home page.");
        jPanel1.add(jLabelDes5, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 670, -1, -1));

        jLabelDesGoHome.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabelDesGoHome.setForeground(new java.awt.Color(153, 255, 255));
        jLabelDesGoHome.setText("HERE");
        jLabelDesGoHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDesGoHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDesGoHomeMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelDesGoHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 670, -1, -1));

        jLabelDes7.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabelDes7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDes7.setText("Click");
        jPanel1.add(jLabelDes7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 670, -1, -1));

        jButtonNational.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonNational.setText("National");
        jButtonNational.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNational.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNationalMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonNational, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        Individual.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Individual.setText("Individual");
        Individual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Individual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IndividualMouseClicked(evt);
            }
        });
        jPanel1.add(Individual, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, -1, -1));

        jLabelPicture.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPicture.setIcon(new javax.swing.ImageIcon("H:\\Java Crime\\CrimeManagement\\Java images\\Duty Officers.jpg")); // NOI18N
        jLabelPicture.setText("jLabel1");
        jLabelPicture.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.add(jLabelPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkRetrieveActionPerformed
        String time = jComboBox1.getSelectedItem().toString();
        int item=Integer.parseInt(time);
        int index=item-1985;
        
        
        String s=String.valueOf(female[index]);
        jTextFieldFemaleOfficer.setText(s);
        s=String.valueOf(male[index]);
        jTextFieldMaleOfficer.setText(s);
        s=String.valueOf(female[index]+male[index]);
        jTextFieldOfficer.setText(s);
        s=String.valueOf(agency[index]);
        jTextFieldAgency.setText(s);
    }//GEN-LAST:event_jButtonOkRetrieveActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMnMouseClicked

    private void jButtonOkRetrieveForThanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkRetrieveForThanaActionPerformed
        String thana = jTextFieldThana.getText();
        jTextFieldThana.setText("");
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT * FROM `users` WHERE `duty zone`=?";
        try{
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, thana);
            rs = ps.executeQuery();
            int flag=0;
            while(rs.next()){
                flag=1;
                
                String Name = rs.getString("name");
                String Place = rs.getString("duty zone");
                String Mobile = rs.getString("mobile number");
                
                Name = Name.toUpperCase();
                Place = Place.toUpperCase();
                
                String tbData[] = {Place,Name};
                DefaultTableModel tblModel = (DefaultTableModel)jTableOfficer.getModel();
                
                tblModel.addRow(tbData);
            }
            if(flag==0){
                JOptionPane.showMessageDialog(null,"No record found");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButtonOkRetrieveForThanaActionPerformed

    private void jLabelDesGoHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDesGoHomeMouseClicked
        HomePageForPolice pgf = new HomePageForPolice();
        pgf.setVisible(true);
        pgf.pack();
        pgf.setLocationRelativeTo(null);
        pgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelDesGoHomeMouseClicked

    private void jButtonNationalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNationalMouseClicked
        jButtonOkRetrieveForThana.setVisible(false);
        jScrollPane1.setVisible(false);
        jTableOfficer.setVisible(false);
        jTextFieldThana.setVisible(false);
        jLabelEnterThana.setVisible(false);
        
        jButtonOkRetrieve.setVisible(true);
        jLabelFemaleOfficer.setVisible(true);
        jLabelMaleOfficer.setVisible(true);
        jLabelOfficer.setVisible(true);
        jLabelAgency.setVisible(true);
        jLabelYear.setVisible(true);
        jTextFieldAgency.setVisible(true);
        jTextFieldFemaleOfficer.setVisible(true);
        jTextFieldMaleOfficer.setVisible(true);
        jTextFieldOfficer.setVisible(true);
        jComboBox1.setVisible(true);
    }//GEN-LAST:event_jButtonNationalMouseClicked

    private void IndividualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IndividualMouseClicked
        jButtonOkRetrieve.setVisible(false);
        jLabelFemaleOfficer.setVisible(false);
        jLabelMaleOfficer.setVisible(false);
        jLabelOfficer.setVisible(false);
        jLabelAgency.setVisible(false);
        jLabelYear.setVisible(false);
        jTextFieldAgency.setVisible(false);
        jTextFieldFemaleOfficer.setVisible(false);
        jTextFieldMaleOfficer.setVisible(false);
        jTextFieldOfficer.setVisible(false);
        jComboBox1.setVisible(false);
        
        jButtonOkRetrieveForThana.setVisible(true);
        jScrollPane1.setVisible(true);
        jTableOfficer.setVisible(true);
        jTextFieldThana.setVisible(true);
        jLabelEnterThana.setVisible(true);
    }//GEN-LAST:event_IndividualMouseClicked

    
    static void mainCaller()throws JSONException{
        BufferedReader reader;
        String line=new String();
        StringBuffer response = new StringBuffer();
        HttpURLConnection connection=null;
        
        try{
            URL u = new URL("https://api.usa.gov/crime/fbi/sapi/api/police-employment/national/1985/2019?api_key=type your API KEY here");
            connection = (HttpURLConnection) u.openConnection();
            
            
            int status = connection.getResponseCode();
            System.out.println("code"+status);
            
            
            if(status>299){
                reader = new BufferedReader(new InputStreamReader(connection.getErrorStream()));
                
                while ((line = reader.readLine()) != null) {
                    response.append(line);
                }
                reader.close();
            }
            else{
                reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
                
                while ((line = reader.readLine()) != null) {
                    response.append(line);
                }
                reader.close();
            }
            //parse(response.toString());
            //System.out.println(response);
        }/*
        catch(Exception e){
            System.out.println(e);
        }*/
        catch(MalformedURLException e){
            e.printStackTrace();
        }
        catch(IOException e){
            e.printStackTrace();
        }
        finally{
            connection.disconnect();
        }
        
        //JSONPerser jsonparser = new JSONPerser();
        
        //JSONObject response = new JSONObject(line);
        
        //System.out.println(response);
        
        JSONObject myResponse = new JSONObject(response.toString());
        //System.out.println(myResponse);
        JSONArray array= (JSONArray)myResponse.get("results");
        System.out.println("Duty Officers");
        System.out.println(array.length());
        
        for(int i=0; i<size; i++){
            JSONObject results = (JSONObject)array.get(i);
            year[i]= (int)results.get("data_year");
            female[i] = (int)results.get("female_officer_ct");
            male[i] = (int)results.get("male_officer_ct");
            agency[i] = (int)results.get("agency_count_pe_submitting");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws JSONException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DutyOfficers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DutyOfficers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DutyOfficers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DutyOfficers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DutyOfficers().setVisible(true);
            }
        });
        mainCaller();
        CrimeRecords.mainCrime();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Individual;
    private javax.swing.JButton jButtonNational;
    private javax.swing.JButton jButtonOkRetrieve;
    private javax.swing.JButton jButtonOkRetrieveForThana;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAgency;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelDes;
    private javax.swing.JLabel jLabelDes1;
    private javax.swing.JLabel jLabelDes2;
    private javax.swing.JLabel jLabelDes3;
    private javax.swing.JLabel jLabelDes4;
    private javax.swing.JLabel jLabelDes5;
    private javax.swing.JLabel jLabelDes7;
    private javax.swing.JLabel jLabelDesGoHome;
    private javax.swing.JLabel jLabelEnterThana;
    private javax.swing.JLabel jLabelFemaleOfficer;
    private javax.swing.JLabel jLabelMaleOfficer;
    private javax.swing.JLabel jLabelMn;
    private javax.swing.JLabel jLabelOfficer;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOfficer;
    private javax.swing.JTextField jTextFieldAgency;
    private javax.swing.JTextField jTextFieldFemaleOfficer;
    private javax.swing.JTextField jTextFieldMaleOfficer;
    private javax.swing.JTextField jTextFieldOfficer;
    private javax.swing.JTextField jTextFieldThana;
    // End of variables declaration//GEN-END:variables
}
