/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crimemanagement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONException;

/**
 *
 * @author User
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabelUsername.setVisible(false);
        jLabelPassword.setVisible(false);
        jTextField_UserName.setVisible(false);
        jTextField_Password.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMn = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextField_Password = new javax.swing.JTextField();
        jButtonRetrieve = new javax.swing.JButton();
        jButtonSendEmail = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField_NidNumber = new javax.swing.JTextField();
        jLabel_GoBackLogin = new javax.swing.JLabel();
        jTextField_UserName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_Code = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(510, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Retrieve Information");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 20, -1));

        jLabelMn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelMn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMn.setText("-");
        jLabelMn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMnMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelMn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, 20));

        jLabelUsername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Username:");
        jPanel2.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabelPassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password:");
        jPanel2.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 403, -1, -1));

        jTextField_Password.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel2.add(jTextField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 310, -1));

        jButtonRetrieve.setBackground(new java.awt.Color(0, 204, 204));
        jButtonRetrieve.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonRetrieve.setText("Retrieve");
        jButtonRetrieve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetrieveActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRetrieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jButtonSendEmail.setBackground(new java.awt.Color(0, 204, 204));
        jButtonSendEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonSendEmail.setText("Send Email");
        jButtonSendEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSendEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NID Number:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, -1, -1));

        jTextField_NidNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jTextField_NidNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 310, -1));

        jLabel_GoBackLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel_GoBackLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_GoBackLogin.setText("Click here to go back to Login Page");
        jLabel_GoBackLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_GoBackLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_GoBackLoginMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel_GoBackLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        jTextField_UserName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel2.add(jTextField_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 310, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, -1, -1));

        jTextField_Email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jTextField_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 310, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Code:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jTextField_Code.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(jTextField_Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 170, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Type your email & NID number, a verification code will be sent to your mail.");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabelPicture.setIcon(new javax.swing.ImageIcon("H:\\Java Crime\\CrimeManagement\\Java images\\Forgot Password.jpg")); // NOI18N
        jLabelPicture.setText("jLabel3");
        jLabelPicture.setPreferredSize(new java.awt.Dimension(510, 500));
        jPanel2.add(jLabelPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMnMouseClicked
    static String code;
    private void jButtonRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetrieveActionPerformed
        String nid = jTextField_NidNumber.getText();
        String mail = jTextField_Email.getText();
        String Checkcode = jTextField_Code.getText();
        jTextField_Code.setText("");
        
        if(code.equals(Checkcode)){
        
            PreparedStatement ps;
            ResultSet rs;
            String query="SELECT * FROM `users` WHERE `NID Number`=?";
        
            try{
            
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, nid);
                rs = ps.executeQuery();
                while(rs.next()){
                    jTextField_UserName.setText(rs.getString("username"));
                    jTextField_Password.setText(rs.getString("password"));
                    jTextField_UserName.setVisible(true);
                    jTextField_Password.setVisible(true); 
                    jLabelUsername.setVisible(true);
                    jLabelPassword.setVisible(true);                   
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Sorry Verification Code didn't match");
        }
    }//GEN-LAST:event_jButtonRetrieveActionPerformed
    
    private void jButtonSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendEmailActionPerformed
        String nid = jTextField_NidNumber.getText();
        String mail = jTextField_Email.getText();
        PreparedStatement ps;
        ResultSet rs;
        
        
        String query= "SELECT * FROM `users` WHERE `mobile number` =? AND `NID number` =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, mail);
            ps.setString(2, nid);
            
            rs = ps.executeQuery();
            
            if(rs.next()){               
                code=EmailSender.emu(mail);
                JOptionPane.showMessageDialog(null, "Email sent successfully. Please check your inbox");
            }
            else{
                JOptionPane.showMessageDialog(null, "Sorry You Provided Wrong Informaation");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //return code;
    }//GEN-LAST:event_jButtonSendEmailActionPerformed

    private void jLabel_GoBackLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_GoBackLoginMouseClicked
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_GoBackLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws JSONException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
        
        DutyOfficers.mainCaller();
        CrimeRecords.mainCrime();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetrieve;
    private javax.swing.JButton jButtonSendEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMn;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabel_GoBackLogin;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_Code;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_NidNumber;
    private javax.swing.JTextField jTextField_Password;
    private javax.swing.JTextField jTextField_UserName;
    // End of variables declaration//GEN-END:variables
}
