/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crimemanagement;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JFrame;


//import java.io.IOException;
//import java.net.URL;
//import java.net.MalformedURLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
//import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.json.*;
//import org.json.JSONObject;

/**
 *
 * @author User
 */
public class PoliceStations extends javax.swing.JFrame {

    /**
     * Creates new form PoliceStations
     */
    
    //static int size =35;
    //static ArrayList<String> name=new ArrayList<String>();
    //static ArrayList<String> type=new ArrayList<String>();
    //static ArrayList<String> state=new ArrayList<String>();
    //static ArrayList<String> division=new ArrayList<String>();
    //static double lat [] = new double[size];
    //static double lang[] = new double[size];
   
    
    public PoliceStations() {
        initComponents();
        setLocationRelativeTo(null);
        jTableStation.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)jTableStation.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        jTableStation.setGridColor(Color.WHITE);
        jTableStation.setForeground(Color.WHITE);
        
        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        jTableStation.setOpaque(false);
        ((DefaultTableCellRenderer)jTableStation.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1stLine = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMn = new javax.swing.JLabel();
        jLabelHeading = new javax.swing.JLabel();
        jLabel3rdLine = new javax.swing.JLabel();
        jLabel4thLine = new javax.swing.JLabel();
        jLabelMapBrowser = new javax.swing.JLabel();
        jLabel1stLine1 = new javax.swing.JLabel();
        jLabel4thLine1 = new javax.swing.JLabel();
        jLabelGoHome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStation = new javax.swing.JTable();
        jButtonSee = new javax.swing.JButton();
        jLabel3rdLine1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelPicture = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 464));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(812, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1stLine.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1stLine.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1stLine.setText("map opens, enter your location to see the nearest stations serially. You can find driving distance, route,");
        jPanel1.add(jLabel1stLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 152, -1, -1));

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabelMn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelMn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMn.setText("-");
        jLabelMn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMnMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 20, 20));

        jLabelHeading.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabelHeading.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHeading.setText("Information of Police Stations");
        jPanel1.add(jLabelHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 70, -1, 38));

        jLabel3rdLine.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3rdLine.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3rdLine.setText("website and hotline number of every police stations.");
        jLabel3rdLine.setInheritsPopupMenu(false);
        jPanel1.add(jLabel3rdLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 174, -1, -1));

        jLabel4thLine.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4thLine.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4thLine.setText("Want to see the map in Browser? Click");
        jPanel1.add(jLabel4thLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 535, -1, -1));

        jLabelMapBrowser.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelMapBrowser.setForeground(new java.awt.Color(153, 255, 204));
        jLabelMapBrowser.setText("HERE");
        jLabelMapBrowser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMapBrowser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMapBrowserMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMapBrowser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 535, -1, -1));

        jLabel1stLine1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1stLine1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1stLine1.setText("You can see all police stations of your country. A map is attached to give better service. Once the");
        jPanel1.add(jLabel1stLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel4thLine1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4thLine1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4thLine1.setText("Want to go back to Home Page? Click");
        jPanel1.add(jLabel4thLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, -1, -1));

        jLabelGoHome.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelGoHome.setForeground(new java.awt.Color(153, 255, 204));
        jLabelGoHome.setText("HERE");
        jLabelGoHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelGoHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGoHomeMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelGoHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane1.setOpaque(false);

        jTableStation.setBackground(new java.awt.Color(0, 0, 0));
        jTableStation.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableStation.setForeground(new java.awt.Color(255, 255, 255));
        jTableStation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Website", "Hotline Number"
            }
        ));
        jTableStation.setGridColor(new java.awt.Color(255, 255, 255));
        jTableStation.setOpaque(false);
        jScrollPane1.setViewportView(jTableStation);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 720, 140));

        jButtonSee.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButtonSee.setText("SEE");
        jButtonSee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSeeMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSee, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jLabel3rdLine1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3rdLine1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3rdLine1.setText("Enter a name:");
        jLabel3rdLine1.setInheritsPopupMenu(false);
        jPanel1.add(jLabel3rdLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 230, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an option", "Kadamtali Police Station", "Mirpur Model Police Station", "Dhanmondi Model Thana", "Dakshinkhan Police Station", "Bangladesh Police Headquarters, Dhaka", "Hazaribagh Police Station", "Gulshan Police Station", "Gazipur Police Station", "Patiya Police Station", "Rupanj Police Thana", "Chauddagram Police Staion", "Sakhipur Police Station", "Dinajpur Police Station", "Agailjhara Police Station", "Savar Model Police Station", "Joypurhat Police Station" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 232, 300, -1));

        jLabelPicture.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPicture.setIcon(new javax.swing.ImageIcon("H:\\Java Crime\\CrimeManagement\\Java images\\Police Stations.jpeg")); // NOI18N
        jLabelPicture.setText("jLabel1");
        jLabelPicture.setPreferredSize(new java.awt.Dimension(810, 464));
        jPanel1.add(jLabelPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMnMouseClicked

    
    File urlDesktop = new File(
                "H:\\Java Crime\\CrimeManagement\\los angeles.html");
    private void jLabelMapBrowserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMapBrowserMouseClicked
        //File urlDesktop = new File("C:\\HTMLGmaps\\bangladesh_police_station.html");
        try {
            Desktop.getDesktop().open(urlDesktop);
        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jLabelMapBrowserMouseClicked

    private void jLabelGoHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGoHomeMouseClicked
        HomePageForPolice pgf = new HomePageForPolice();
        pgf.setVisible(true);
        pgf.pack();
        pgf.setLocationRelativeTo(null);
        pgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelGoHomeMouseClicked

    private void jButtonSeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSeeMouseClicked
        
        String name = jComboBox1.getSelectedItem().toString();
        
        PreparedStatement ps;
        ResultSet rs;
        String query="SELECT * FROM `police stations` WHERE `Name`=?";
        try{
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, name);
            rs = ps.executeQuery();
            int flag=0;
            while(rs.next()){
                flag=1;
                
                String Name = rs.getString("Name");
                String Website = rs.getString("Website");
                String Address = rs.getString("Address");
                String Mobile = rs.getString("Hotline Number");
                
                
                
                String tbData[] = {Name,Address,Website,Mobile};
                DefaultTableModel tblModel = (DefaultTableModel)jTableStation.getModel();
                
                tblModel.addRow(tbData);
            }
            if(flag==0){
                JOptionPane.showMessageDialog(null,"No record found");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButtonSeeMouseClicked
    /*
    static void setTable(){
        jTableStation.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)jTableStation.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        jTableStation.setGridColor(Color.WHITE);
        jTableStation.setForeground(Color.WHITE);
        
        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        jTableStation.setOpaque(false);
        ((DefaultTableCellRenderer)jTableStation.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws JSONException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliceStations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliceStations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliceStations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliceStations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliceStations().setVisible(true);
            }
        });
        DutyOfficers.mainCaller();
        CrimeRecords.mainCrime();
        //setTable();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSee;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1stLine;
    private javax.swing.JLabel jLabel1stLine1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3rdLine;
    private javax.swing.JLabel jLabel3rdLine1;
    private javax.swing.JLabel jLabel4thLine;
    private javax.swing.JLabel jLabel4thLine1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelGoHome;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelMapBrowser;
    private javax.swing.JLabel jLabelMn;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStation;
    // End of variables declaration//GEN-END:variables
}
