/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
package crimemanagement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONException;
        
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMn = new javax.swing.JLabel();
        jLabelHeading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNidNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDutyZone = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelPicture = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jPasswordFieldConPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(950, 476));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelClose.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel3.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 27, -1, -1));

        jLabelMn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelMn.setText("-");
        jLabelMn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMnMouseClicked(evt);
            }
        });
        jPanel3.add(jLabelMn, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 27, 17, -1));

        jLabelHeading.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelHeading.setText("Sign Up");
        jPanel3.add(jLabelHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 26, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Name:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 105, -1, -1));

        jTextFieldName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 102, 276, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Duty Zone:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 197, -1, -1));

        jTextFieldNidNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(jTextFieldNidNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 148, 276, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("NID Number:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 151, -1, -1));

        jTextFieldDutyZone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(jTextFieldDutyZone, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 194, 276, -1));

        jTextFieldEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 240, 276, -1));

        jTextFieldUsername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 286, 276, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Email Address:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 243, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Username:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 289, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Password:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 335, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Confirm Password;");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 381, -1, -1));

        jLabelPicture.setIcon(new javax.swing.ImageIcon("H:\\Java Crime\\CrimeManagement\\Java images\\Registration Form.jpeg")); // NOI18N
        jLabelPicture.setText("jLabel8");
        jLabelPicture.setPreferredSize(new java.awt.Dimension(450, 416));
        jPanel3.add(jLabelPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Go Back to");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 430, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Login Page");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 430, -1, -1));

        jButtonRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(0, 204, 204));
        jButtonRegister.setText("Register");
        jButtonRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegisterMouseClicked(evt);
            }
        });
        jPanel3.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, -1));

        jButtonCancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });
        jPanel3.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*All fields are required");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jPasswordFieldPass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(jPasswordFieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 332, 276, -1));

        jPasswordFieldConPass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(jPasswordFieldConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 378, 276, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        LoginForm rgf= new LoginForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMnMouseClicked

    static int NID(String nid){
        PreparedStatement ps;
        ResultSet rs;
        int ans=0;
        String query= "SELECT * FROM `users` WHERE `NID number` =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, nid);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                ///JOptionPane.showMessageDialog(null,"Login Successful");
                ans=1;
            }
            else{
                ans=0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ans;
    }
    
    static int NIDVer(String nid){
        PreparedStatement ps;
        ResultSet rs;
        int ans=0;
        String query= "SELECT * FROM `nid` WHERE `NID` =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, nid);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                ///This NID is Valid
                ans=1;
            }
            else{
                ans=0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ans;
    }
    
    static int userver(String user){
        PreparedStatement ps;
        ResultSet rs;
        int ans=0;
        String query= "SELECT * FROM `users` WHERE `username` =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, user);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                ///JOptionPane.showMessageDialog(null,"Login Successful");
                ans=1;
            }
            else{
                ans=0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ans;
    }
    
    static int number(String number){
        PreparedStatement ps;
        ResultSet rs;
        int ans=0;
        String query= "SELECT * FROM `users` WHERE `mobile number` =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, number);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                ///JOptionPane.showMessageDialog(null,"Login Successful");
                ans=1;
            }
            else{
                ans=0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ans;
    }
    
    private void jButtonRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterMouseClicked
        String name = jTextFieldName.getText();
        String nid = jTextFieldNidNumber.getText();
        String mobile = jTextFieldEmail.getText();
        String place = jTextFieldDutyZone.getText();
        String pass = jPasswordFieldPass.getText();
        String conpass = jPasswordFieldConPass.getText();
        String username = jTextFieldUsername.getText();
        
        name=name.toUpperCase();
        place=place.toUpperCase();

        if(name.equals("") | nid.equals("") | mobile.equals("") | place.equals("") | username.equals("") | pass.equals("") | conpass.equals("")){
            JOptionPane.showMessageDialog(null, "One or more fields are empty");
        }
        /*
        else if(){
            JOptionPane.showMessageDialog(null, "Please provide NID Number");
        }*/
        
        else if(NID(nid)==1){
            JOptionPane.showMessageDialog(null, "You already have an account with this NID Number");
        }
        
        else if(NIDVer(nid)==0){
            JOptionPane.showMessageDialog(null, "Sorry, this NID Number doesn't belong to any police personnel");
        }
        /*
        else if(){
            JOptionPane.showMessageDialog(null, "Please insert your Email Address");
        }*/
        
        else if(number(mobile)==1){
            JOptionPane.showMessageDialog(null, "This Email Address has been used before to open an account");
        }
        
        else if(ValidateAnEmail.valEmail(mobile)==false){
            JOptionPane.showMessageDialog(null, "This is not a valid Email Address");
        }
        /*
        else if(){
            JOptionPane.showMessageDialog(null, "Please mention your duty zone");
        }
        
        else if(){
            JOptionPane.showMessageDialog(null, "Please Provide a username");
        }*/
        
        else if(userver(username)==1){
            JOptionPane.showMessageDialog(null, "This username is already taken, try another one");
        }
        /*
        else if(){
            JOptionPane.showMessageDialog(null, "Please insert a password");
        }*/
        
        else if(pass.length()<8 | pass.length()>32){
            JOptionPane.showMessageDialog(null, "password must be at least 8 characters long and within 32 charcaters");
        }
        /*
        else if(){
            JOptionPane.showMessageDialog(null, "Please confirm password");
        }*/
        
        else if(!pass.equals(conpass)){
            JOptionPane.showMessageDialog(null, "Please retype your password again correctly");
        }
        

        else{
            PreparedStatement st;

            String qry="INSERT INTO `users`(`name`, `NID number`, `duty zone`, `mobile number`, `username`, `password`, `confirm password`) VALUES (?,?,?,?,?,?,?)";
            try{
                st = MyConnection.getConnection().prepareStatement(qry);

                st.setString(1,name);
                st.setString(2,nid);
                st.setString(3,place);
                st.setString(4,mobile);
                st.setString(5,username);
                st.setString(6,pass);
                st.setString(7,conpass);
                //st.setString(8, null);

                if(st.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "Registration Successful. Go Back to Login Page");
                    jTextFieldName.setText("");
                    jTextFieldNidNumber.setText("");
                    jTextFieldEmail.setText("");
                    jTextFieldDutyZone.setText("");
                    jTextFieldUsername.setText("");
                    jPasswordFieldPass.setText("");
                    jPasswordFieldConPass.setText("");
                }

            }catch (SQLException ex){
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
    }//GEN-LAST:event_jButtonRegisterMouseClicked

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
        HomePageForPolice rgf= new HomePageForPolice();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelMouseClicked

    /**/    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws JSONException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
        DutyOfficers.mainCaller();
        CrimeRecords.mainCrime();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelMn;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldConPass;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldDutyZone;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNidNumber;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
